version: '3.8'

services:
  uptime-kuma:
    image: louislam/uptime-kuma:latest
    container_name: uptime-kuma
    restart: unless-stopped
    ports:
      - "3001:3001"  # Uptime Kuma 默认端口
    volumes:
      - uptime-kuma-data:/app/data
    environment:
      - TZ=Asia/Shanghai  # 设置时区，根据需要调整

volumes:
  uptime-kuma-data: